### ISSUE TITLE
Custom Notification Sound

### ISSUE THREAD

**Issue by DeepeshKalura** [vjousse/pomodorolm#122]
# Currently

![image](https://github.com/user-attachments/assets/113d4c8c-2ac0-47f9-ac53-4ec5e66f3514)
I was able to fund ring notification every break and work 

But most of the time  I am unable to hear because it was super short. Therefore I need a a feature to add my custome Notification Sound.

**Comment by vjousse** [comment]
Could you tell me what version you are using? How did you replace the current sound? And could you give here the new sound you are using?

**Comment by DeepeshKalura** [comment]
I am not well with JS but when my exam get over  I can contribute to create this feature.

**Comment by vjousse** [comment]
Thanks for the clarification, I misunderstood your issue!

Got it, I'll see how I can implement that, you're not the one asking for such feature :+1:

**Comment by vjousse** [comment]
@DeepeshKalura this is implemented in the new 0.3.0 release

**Comment by DeepeshKalura** [comment]
@vjousse  Thanks man
