### ISSUE TITLE
MacOS : window remains in alt-tab list after minimizing to tray

### ISSUE THREAD

**Issue by nxmndr** [vjousse/pomodorolm#131]
## 🪲 Describe the bug
The window disappears and the tray icon appears, but the icon remains in the alt-tab list of open windows, and stil has that MacOS "focus" (with MacOS upper bar "pomodorolm" visible) despite being invisible. Cmd+Q quits.

## 📑 To Reproduce
Enable minimize to tray in settings and close the window.

## ☑️ Expected behavior
Same but be invisible in alt-tab list and no MacOS focus / invisible window.

## 🧑‍💻 Desktop
 - OS: MacOS
 - Version 11.5.2

## 🍅 Pomodorolm information
Install : via Github .dmg
Version : 0.3.0

Merci :)

**Comment by vjousse** [comment]
Thanks for the report! Was it already the case with earlier versions of pomodorolm, especially before 0.2.0? (I can't easily test on macos as I’m on Linux)

**Comment by vjousse** [comment]
It should be fixed in the latest `0.3.1` release @nxmndr https://github.com/vjousse/pomodorolm/releases/tag/app-v0.3.1
Let me know if it works for you!

**Comment by nxmndr** [comment]
Ça fonctionne merci.

0.1.11 et 0.2.0 plantent sur Macos 11.5.2 :

```
/Applications/pomodorolm.app/Contents/MacOS/pomodorolm ; exit;
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-rc.15/src/app.rs:1096:11:
Failed to setup app: error encountered during setup hook: TOML parse error at line 1, column 1
  |
1 | always_on_top = true
  | ^^^^^^^^^^^^^^^^^^^^
missing field `pomodoro_duration`
```

**Comment by vjousse** [comment]
Avec plaisir, merci pour l’issue !
