### ISSUE TITLE
One of “Minimize to Tray” and “Minimize to Tray on Close” is redundant

### ISSUE THREAD

**Issue by GrimPixel** [vjousse/pomodorolm#30]
From what I perceive, both “Minimize to Tray” and “Minimize to Tray on Close” do the same thing. When “Minimize to Tray” is on, it is supposed that the window can be minimised by clicking on the “minimize” icon; when “Minimize to Tray on Close” is on, it is supposed that the window can be minimised by clicking on the “close” icon. 

I think “Minimize to Tray on Close” is redundant. On Arch Linux, both options don't work at all: either on or off, “minimize” icon minimises the window to tray, “close” icon closes the program.

**Comment by vjousse** [comment]
Thanks for the report! What Desktop environnement are you using?

**Comment by GrimPixel** [comment]
That's MATE.

**Comment by vjousse** [comment]
I've released the 0.0.4 version on aur that should fix this bug https://aur.archlinux.org/packages/pomodorolm-bin
